stack:
  nginx:
    index: index.php

  php:
    version: 5.6
    modules:
      - curl
      - gd
      - intl
      - mbstring
      - mcrypt
#      - mhash
      - hash
      - openssl
      - pdo_mysql
      - soap
      - xml
      - xsl
      - zip

  mysql:
    version: 5.5
    user: magento
    password: magento
    databases:
      - magento

deployment:
  install:
    - composer install --prefer-dist --no-interaction --optimize-autoloader
    - chown -R :www-data .
    - find . -type d -exec chmod 755 {} \; && sudo find . -type f -exec chmod 644 {} \; && sudo chmod u+x bin/magento; sudo chmod -R g+w ./{pub,var}; sudo chmod -R g+s ./{pub,var}
